# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/instance: actions-runner-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/version: 0.26.0
type: Opaque
data:
  github_app_id: 11111
  github_app_installation_id: 1111
  github_app_private_key: |
    1111111